# Postgres Connection

# version: '3.8'
# services:
#   dev-db:
#     image: postgres:13
#     ports:
#       - 5434:5432
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 123
#       POSTGRES_DB: nest
#     networks:
#       - yashcode
# networks:
#   yashcode:

# MySQL Connection

version: '3.8'
services:
  dev-db:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: nest
    networks:
      - yashcode
networks:
  yashcode:
